#!/usr/bin/env python

import os
import sys

import ROOT

# Because ROOT can't be bothered to ship a CLI tool to view trees.

def printTreeLeaves(tree):
	leaves = tree.GetListOfLeaves()
	leaves.Print()

def printKeyList(object, keys):
	iterator = ROOT.TListIter(keys)
	nextKey = iterator.Next()
	while not nextKey is None and nextKey != None:
		keyName = nextKey.GetName()
		try:
			newObject = object.Get(keyName)
			if isinstance(newObject, ROOT.TTree):
				printTreeLeaves(newObject)
			else:
				newObject.Print()
		except:
			pass
		nextKey.Print()
		nextKey = iterator.Next()

def main():

	try:
		treename = sys.argv[1]
		treename = os.path.abspath(treename)
		tfile = ROOT.TFile(treename)
		keys = tfile.GetListOfKeys()
		printKeyList(tfile, keys)
		tfile.Close()
	except IOError:
		print "Error: invalid file specified."

if __name__ == '__main__':
	main()
